switch test to finish
HubertKwiatkowski/ui-system pull request #10
Opened 2023-02-11 20:23 UTC by HubertKwiatkowski

zostawilem komentarz przy elemencie, ktorego nie moge rozgryzc

2023-02-11 20:47 UTC, Sumick requested changes
Tests looks great! This one test does not work because `onChange` is probably not passed correctly to the input. Ensure that you pass `onChange` properly

2023-02-11 20:47 UTC, Sumick commented on src/inputs/Switch/Switch.test.tsx
> +  expect(handleChange).toBeCalled();
**issue:** Looks like your `onChange` is not working correctly on the input. Ensure that you pass it correctly in your `Switch` input. It's a probably a bug in the component.

2023-02-12 10:44 UTC, HubertKwiatkowski commented
![image](https://user-images.githubusercontent.com/63370430/218306196-cfae6e05-423b-4406-b3b1-da3401fe420a.png)

po wprowadzeniu sugerowanych poprawek, pierwszy test dziala poprawnie, drugi wyklada sie na ostatniej linijce... pomimo, ze switch jest disabled... wydaje mi sie, ze wszystko jest teraz skonstruowawne jak checkbox; jakis pomysl, gdzie jeszcze moge miec blad?

2023-02-12 13:57 UTC, Sumick reviewed
To make this test work, you can make something like this (in your input) to prevent handler from being called:

<img width="306" alt="Zrzut ekranu 2023-02-12 o 14 56 39" src="https://user-images.githubusercontent.com/22893188/218315311-2ae23b15-2a81-48b7-adc6-86f96e07cedf.png">

2023-02-12 14:06 UTC, HubertKwiatkowski commented
no tak, porownywalem kod na branchu switchTest, gdzie nie mialem zaktualizowanego kodu dla checkboxa... chyba za duzo testow ostatnio... :D

2023-02-12 14:40 UTC, Sumick approved these changes
Great job! Looks good now

2023-02-12 14:54 UTC, merged